DROP DATABASE ramt;
CREATE DATABASE ramt;
\connect ramt

SET timezone = 'America/Los_Angeles';

CREATE OR REPLACE FUNCTION update_time_created_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.time_created = CURRENT_TIMESTAMP; 
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TABLE users (
  email TEXT PRIMARY KEY
    CHECK (position('@' IN email) > 1),
  username VARCHAR(15) NOT NULL,
  password TEXT NOT NULL,
  profile_pic TEXT NOT NULL
);

CREATE TABLE userHistory (
  Personid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  item TEXT NOT NULL,
  score INT NOT NULL,
  email TEXT NOT NULL,
  time_created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (email) REFERENCES users ON DELETE CASCADE
);

CREATE TABLE history (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  item TEXT NOT NULL,
  score INT NOT NULL,
  time_created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  popularity INT DEFAULT 0
);

CREATE TRIGGER update_history_time_created BEFORE UPDATE
ON history FOR EACH ROW EXECUTE PROCEDURE 
update_time_created_column();